#!/bin/bash
# Simple cron-based process heartbeat. Should use Monit in future: http://mmonit.com/monit/
if ! [ /etc/init.d/bamboo-agent status | grep -q "Bamboo Agent is running" ]
  /etc/init.d/bamboo-agent start
fi

