#!/bin/bash
# Outputs a list of the yum packages needed for ruby and cucumber.
# ----------------------------------------------------------------
ruby_packages="ruby ruby-devel gcc rubygems"
cucumber_packages="libxml2 libxml2-devel libxslt libxslt-devel xorg-x11-server-Xvfb firefox ImageMagick"
echo "$ruby_packages $cucumber_packages"

